# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: mbhein
name: include_beer
version: 0.1.0
readme: README.md
authors:
  - Matthew Hein (github.com/mbhein)
description: null
license_file: COPYING
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - include_beer
  - raspberry_pi
repository: https://github.com/mbhein/ansible-collection-include-beer
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/mbhein/ansible-collection-include-beer
issues: https://github.com/mbhein/ansible-collection-include-beer/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
