---
- name: Converge
  hosts: all
  tasks:
    - name: "Show Ansible Distribution"
      debug:
        msg: "{{ ansible_facts.distribution }} - {{ ansible_facts.distribution_version }}"

    - name: "Include podman"
      include_role:
        name: "podman"
