---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian_buster
    image: debian:buster
    dockerfile: ../resources/Dockerfile.j2
    pre_build_image: false
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible
